#设置启用的环境
spring:
  profiles:
    active: ${profile.active}

---
#生产
spring:
  profiles: pro
server:
  port: 80

---
#开发
spring:
  profiles: dev
server:
  port: 81
---
#测试
spring:
  profiles: test
server:
  port: 82